### ISSUE TITLE
win10运行python -m pip install -r requirements.txt后出错

### ISSUE THREAD

**Issue by thankeyes** [boytm/minivtun-win#2]
安装报错,请问这个要如何解决?
(BTW:请问大佬可以做一个exe版本么?可以直接cmd命令运行就太棒了)

./python -m pip install -r requirements.txt

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: wheel in c:\python27\lib\site-packages (from -r requirements.txt (line 1)) (0.37.1)
Requirement already satisfied: ipaddress in c:\python27\lib\site-packages (from -r requirements.txt (line 2)) (1.0.23)
Requirement already satisfied: pywin32 in c:\python27\lib\site-packages (from -r requirements.txt (line 3)) (228)
Requirement already satisfied: wmi in c:\python27\lib\site-packages (from -r requirements.txt (line 4)) (1.5.1)
Collecting M2Crypto
  Using cached M2Crypto-0.38.0.tar.gz (1.2 MB)
Requirement already satisfied: typing in c:\python27\lib\site-packages (from M2Crypto->-r requirements.txt (line 5)) (3.10.0.0)
Building wheels for collected packages: M2Crypto
  Building wheel for M2Crypto (setup.py) ... error

 ERROR: Command errored out with exit status 1:
   command: 'C:\Python27\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\mk\\appdata\\local\\temp\\pip-install-kibce_\\m2crypto\\setup.py'"'"'; __file__='"'"'c:\\users\\mk\\appdata\\local\\temp\\pip-install-kibce_\\m2crypto\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\mk\appdata\local\temp\pip-wheel-yybfop'
       cwd: c:\users\mk\appdata\local\temp\pip-install-kibce_\m2crypto\
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  copying src\M2Crypto\ASN1.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\AuthCookie.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\BIO.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\BN.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\callback.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\DH.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\DSA.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\EC.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\Engine.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\Err.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\EVP.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\ftpslib.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\httpslib.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\m2.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\m2crypto.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\m2urllib.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\m2urllib2.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\m2xmlrpclib.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\Rand.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\RC4.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\RSA.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\six.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\SMIME.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\threading.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\util.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\X509.py -> build\lib.win-amd64-2.7\M2Crypto
  copying src\M2Crypto\__init__.py -> build\lib.win-amd64-2.7\M2Crypto
  creating build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\cb.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\Checker.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\Cipher.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\Connection.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\Context.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\Session.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\SSLServer.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\ssl_dispatcher.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\timeout.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\TwistedProtocolWrapper.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  copying src\M2Crypto\SSL\__init__.py -> build\lib.win-amd64-2.7\M2Crypto\SSL
  running egg_info
  writing requirements to src\M2Crypto.egg-info\requires.txt
  writing src\M2Crypto.egg-info\PKG-INFO
  writing top-level names to src\M2Crypto.egg-info\top_level.txt
  writing dependency_links to src\M2Crypto.egg-info\dependency_links.txt
  reading manifest file 'src\M2Crypto.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'SWIG\*.i'
  warning: no files found matching 'SWIG\*.h'
  warning: no files found matching 'SWIG\*.def'
  warning: no files found matching 'SWIG\_m2crypto_wrap.c'
  warning: no files found matching 'M2Crypto\m2crypto.py'
  writing manifest file 'src\M2Crypto.egg-info\SOURCES.txt'
  running build_ext
  building 'M2Crypto._m2crypto' extension
  swigging src/SWIG/_m2crypto.i to src/SWIG/_m2crypto_wrap.c
  swig.exe -python -IC:\Python27\include -IC:\Python27\PC -I/usr/include/openssl -includeall -modern -builtin -outdir c:\users\mk\appdata\local\temp\pip-install-kibce_\m2crypto\src\M2Crypto -o src/SWIG/_m2crypto_wrap.c src/SWIG/_m2crypto.i
  error: command 'swig.exe' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for M2Crypto

**Comment by boytm** [comment]
[Release  里面](https://github.com/boytm/minivtun-win/releases/download/v0.1/minivtun-win_py27.zip)有打包好的二进制，下载后执行里面 tun.exe 即可。

**Comment by thankeyes** [comment]
win10 64位系统
用管理员模式打开的powershell,直接执行tun.exe,会报错额

PS D:\minivtun-win_py27\dist> .\tun.exe -r 192.168.1.1:51544 -a 10.19.250.188/24 -e 10.19.250 -m 1420 -t rc4 -d
Traceback (most recent call last):
  File "tun.py", line 108, in <module>
  File "M2Crypto\__init__.pyo", line 22, in <module>
  File "M2Crypto\__m2crypto.pyo", line 12, in <module>
  File "M2Crypto\__m2crypto.pyo", line 10, in __load
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。
